### ISSUE TITLE
Improve error handling on bad port

### ISSUE THREAD

**Issue by yoshuawuyts** [clap-rs/clap-port-flag#5]
When we pass a bad port, we should probably provide better error handling than what we currently have. I'm thinking using `failure`'s `.context()` method here might help clarify the errors somewhat.

![2018-07-09-164901_1920x1080](https://user-images.githubusercontent.com/2467194/42457543-056c961a-8398-11e8-9ff5-b16d26b78e75.png)

**Comment by killercup** [comment]
I agree with the general idea. Adding failure as a dependency might be a bit heavy if you just want to wrap one specific error.

**Comment by spacekookie** [comment]
To be honest, the number of errors that can occur here is pretty low. We could just write descriptions for all of them.

At that point we could even let the user pass in an "error description collection" or something that makes it all translatable

**Comment by yoshuawuyts** [comment]
Hehe, yeah I was thinking Failure + Error / Errorkind would be a good fit here: https://boats.gitlab.io/failure/error-errorkind.html

**Comment by matthiasbeyer** [comment]
I'm closing this now as (AFAICS) it is outdated.
