### ISSUE TITLE
Include documentation about which values `--address` accepts

### ISSUE THREAD

**Issue by yoshuawuyts** [clap-rs/clap-port-flag#6]
accepts all strings that can be parsed to ipv4 or ipv6, defaults to localhost. As per https://github.com/rust-clique/clap-port-flag/pull/2, it would be best if we could not include it in `--help` output, but the information could be extracted for man pages.

**Comment by matthiasbeyer** [comment]
I think this is resolved. Feel free to re-open or comment if you think it is not.
